# Generated by Django 4.0.1 on 2022-02-06 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Coin Symbol')),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=15)),
                ('entry_amount', models.DecimalField(decimal_places=10, max_digits=15)),
                ('entry_date', models.DateField(blank=True)),
                ('sold', models.BooleanField(default=False)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=15)),
                ('exit_date', models.DateField(blank=True)),
                ('trader', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
