# Generated by Django 4.0.2 on 2022-02-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_holding_entry_date_alter_holding_exit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='coin_id',
            field=models.CharField(default='1', max_length=50, verbose_name='Coin ID for API'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='entry_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='exit_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
