# Generated by Django 4.0.2 on 2022-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_holding_coin_id_alter_holding_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='entry_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
    ]
