# Generated by Django 4.0.2 on 2022-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_holding_entry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15),
        ),
    ]
